MessagerMVC/Controllers/LogInController.cs
using MessagerMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using MessagerMVC.Services;

namespace MessagerMVC.Controllers
{
    public class LogInController : Controller
    {
        private readonly ILogger<LogInController> _logger;

        public LogInController(ILogger<LogInController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult LogInPage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LogInPage(User user)
        {
            if(ModelState.IsValid && user != null)
            {
                var userService = new UserService();
                switch(userService.AuthenticationUser(user))
                {
                    case true: 
                        {
                            user = userService.GetUserByName(user.Name);
                            SessionService.AddUserToSession(user, HttpContext);
                            return RedirectToAction("HomePage","Home");
                        }
                    case false:
                        { 
                            ViewData["Error"] = "пользователь не найден";
                            return View();
                        } 
                    case null: 
                        { 
                            ViewData["Error"] = "Ошибка сервера!";
                            return View();
                        } 
                }               
            }
            else
                return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MessagerMVC/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using MessagerMVC.Models;
using MessagerMVC.Services;

namespace MessagerMVC.Controllers
{
    public class RegistrationController : Controller
    {
        [HttpGet]
        public IActionResult RegistrationPage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegistrationPage(RegistrationUserModel userModel)
        {
            if(ModelState.IsValid && userModel != null)
            {
                var userService = new UserService();
                User user = userService.ConvertRegistrationUserModelToUser(userModel);

                switch (userService.IsUserNameExists(user.Name))
                {
                    case true: { ViewData["Error"] = "Пользователь с таким именем уже существует"; return View(); } break;
                    case false: break;
                    case null: { ViewData["Error"] = "Ошибка сервера, пользователь не был добавлен!"; return View(); } break;
                }

                userService.AddUserToDB(user);
                return RedirectToAction("RegistrationAcceptPage", userModel);
            }

            ViewData["Error"] = "Заполните все поля!";
            return View();
        }

        [HttpGet]
        public IActionResult RegistrationAcceptPage(RegistrationUserModel user)
        {
            return View(user);
        }
    }
}

MessagerMVC/Views/LogIn/LogInPage.cshtml
@model User
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width" />
    <title>HomePage</title>
    <link href="~/css/site.css" rel ="sitestyle"/>

   
</head>
<body>
 
 <section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your login and password!</p>

              <form asp-controller="LogIn" asp-action="LogInPage" method="post">
                <div class="form-outline form-white mb-4">
                     <input type="text"  asp-for="Name" class="form-control form-control-lg" />
                     <label class="form-label" asp-for="Name">Name</label>
                </div>

                <div class="form-outline form-white mb-4">
                     <input type = "Password" asp-for="Password"  id="typePasswordX" class="form-control form-control-lg" />
                     <label class="form-label" asp-for="Password">Password</label>
                </div>
>

                <button class="btn btn-outline-light btn-lg px-5" type="submit" >Login</button>
              </form> 
             

            </div>

            <div>
              <p class="mb-0">Don't have an account? <a  class="text-white-50 fw-bold" asp-controller="Registration" asp-action="RegistrationPage" method="get">Registration</a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

</body>
</html>